### ISSUE TITLE
GAME FILE ERROR 

### ISSUE THREAD

**Issue by chizzythegoat** [ColombianGuy/r5_aimtrainer#10]
everytime i start a sever it sends me back to main and i get this {Client/cl/utility_menu.gnut #561 [CLIENT] HudElement "ChallengesStatsFrame" could not be found on panel CHudScripElement

**Comment by CoolSlimbo** [comment]
Please consult the common errors channel of the discord. This is an issue of you not installing correctly. Closing it because it’s not the aim trainer.
