### ISSUE TITLE
Crash on connection

### ISSUE THREAD

**Issue by scerelli** [ColombianGuy/r5_aimtrainer#2]
Hi, I was having this problem on my dedi server

```
340.798] Script(S):SCRIPT ERROR: [SERVER] Index "0" is beyond array size of 0
[340.799] Script(S): -> surf.selectedLocation = surf.locationSettings[0]
[340.799] Script(S):
CALLSTACK
*FUNCTION [RunSURF()] gamemodes/custom_surf/_gamemode_surf.nut line [43]

[340.799] Script(S):LOCALS
[this] TABLE

DIAGPRINTS
```

i checked also the script code but couldn't find a way to fix the location problem. The array is obviously empty but maybe we can provide a  fallback here?

maybe could be also related to the map not being managed in the game script (drop off)

**Comment by CoolSlimbo** [comment]
Hey, it seems you’re attempting to run the surf gamemode. That has nothing to do with the Aim Trainer. If you’d like help with it, ask a question first in the discord.

And in relation to why it’s happening. It’s because you’re using a map that doesn’t have anything configured for it yet.
