### ISSUE TITLE
Close Fast Strafes spawn targets way too far away now since last update

### ISSUE THREAD

**Issue by TCM-U** [ColombianGuy/r5_aimtrainer#22]
After installing the latest SDK and updating the aimtrainer files, this issue has appeared. Additionally, when attempting to get closer to the dummy, the dummy backs off until the previous distance has been reached. See the title and video below.

https://user-images.githubusercontent.com/114257629/192043011-accdee0b-da67-4c0b-b60b-bea34ea81146.mp4

**Comment by CafeFPS** [comment]
Thanks for letting me know. I'll take a look asap

**Comment by CafeFPS** [comment]
Hello, I reviewed this and everything seem to be acting as intended. Make sure you modify the spawn distance using the slider in settings page.
