### ISSUE TITLE
Wrong PlaylistVar

### ISSUE THREAD

**Issue by dxalyjz** [ColombianGuy/r5_aimtrainer#25]
`void function WpnPulloutOnRespawn(entity player, float duration)
{
	if(!IsValid( player ) || !IsAlive(player) ) return

	
	if(GetCurrentPlaylistVarBool("flowstateReloadUltimateOnRespawn", false ))
	{
		entity tactical = player.GetOffhandWeapon( OFFHAND_TACTICAL )
		tactical.SetWeaponPrimaryClipCount( tactical.GetWeaponPrimaryClipCountMax() )
	}
	if(GetCurrentPlaylistVarBool("flowstateReloadTacticalOnRespawn", false ))
	{	
		entity ultimate = player.GetOffhandWeapon( OFFHAND_ULTIMATE )
		ultimate.SetWeaponPrimaryClipCount( ultimate.GetWeaponPrimaryClipCountMax() )
	}
	
	if(IsValid( player.GetNormalWeapon( WEAPON_INVENTORY_SLOT_PRIMARY_1 )))
	{
		entity weapon = player.GetNormalWeapon( WEAPON_INVENTORY_SLOT_PRIMARY_1 )
		weapon.SetWeaponCharm( $"mdl/props/charm/charm_nessy.rmdl", "CHARM")
	}
	if(IsValid( player.GetNormalWeapon( WEAPON_INVENTORY_SLOT_PRIMARY_0 )))
	{
		entity weapon = player.GetNormalWeapon( WEAPON_INVENTORY_SLOT_PRIMARY_0 )
		weapon.SetWeaponCharm( $"mdl/props/charm/charm_nessy.rmdl", "CHARM")
		player.SetActiveWeaponBySlot(eActiveInventorySlot.mainHand, WEAPON_INVENTORY_SLOT_PRIMARY_0)
	}
	player.ClearFirstDeployForAllWeapons()
	HolsterAndDisableWeapons(player)
	wait duration-0.5
	if(IsValid(player))
		DeployAndEnableWeapons(player)
}`
flowstateReloadUltimateOnRespawn and flowstateReloadTacticalOnRespawn in wrong position. fix it pls in next release

**Comment by CafeFPS** [comment]
FIxed, thanks
