### ISSUE TITLE
The index "customer_aimtrainer" does not exist

### ISSUE THREAD

**Issue by bverkron** [ColombianGuy/r5_aimtrainer#3]
Just setup R5, SDK, and r5_aimtrainer from scratch. Could be a setup issue on my end but when I try to launch the aimtrainer playlist on the default KC map I get `The index "customer_aimtrainer" does not exist` as per the screenshot.

![image](https://user-images.githubusercontent.com/19174503/189268821-5d44fead-7656-4b94-814f-83568ae974fb.png)

The setup steps I followed were:
* Download / extract latest R5 from here: https://download.r5reloaded.com/r5reloaded.rar (R5pc_r5launch_N1094_CL456479_2019_10_30_05_20_PM)
* Download latest SDK at the time from here: https://github.com/Mauler125/r5sdk/releases/tag/v2.1_b2, unpacked and copied to R5 root folder. I'm able to launch and play R5 fine at this point. Tested on default KC map
* Downloaded aimtrainer files from here https://github.com/ColombianGuy/r5_aimtrainer/releases/download/Release/AimTrainerRequiredFiles.zip and copied the 3 files to the specified locations

**Comment by CafeFPS** [comment]
Read instructions, join the discord channel if you have more questions.

**Comment by jamcmich** [comment]
Hi @ColombianGuy :wave:,

~~I'm having the same issue/error as @bverkron . I followed all the steps with a new installation of the game. The error code I'm getting is ``_settings.nut #625 [SERVER] The index "custom_aimtrainer" does not exist``.~~

~~Is it possible that I need to run a clean installation of the game at least one time before installing the custom playlist?~~

**EDIT:** @bverkron

I solved the issue by downloading the source code from the repository's main page. If you see ``custom_aimtrainer`` in the playlist and not ``Flowstate Aim Trainer``, then you need to deleted all the files in your scripts folder and replace them with the scripts files from the Aim Trainer GitHub here: https://github.com/ColombianGuy/r5_aimtrainer
