### ISSUE TITLE
Bots in "Running Targets" challenge are too far away after a while

### ISSUE THREAD

**Issue by lgmdor** [ColombianGuy/r5_aimtrainer#6]
If you play the "Running Targets" challenge with an infinite timer, after a few minutes most bots will be very far away from the player which makes them almost impossible to kill. Maybe just despawn bots after some time so they can respawn closer to the player?

**Comment by HaloGamer33** [comment]
I agree with this

**Comment by CafeFPS** [comment]
Last commit fixes it
