### ISSUE TITLE
FS 3.71 can`t launch playlist firingrange

### ISSUE THREAD

**Issue by diaoyugan** [ColombianGuy/r5_aimtrainer#79]
[1029.152] Script(S):SCRIPT ERROR: [SERVER] Index "5" is beyond array size of 5
[1029.152] Script(S): -> entity r = file.rackSpawns[ammoIndex].point
[1029.154] Script(S):
CALLSTACK
*FUNCTION [SpawnAttachments()] mp/firing_range.gnut line [547]
*FUNCTION [OnEntitiesDidLoad()] mp/firing_range.gnut line [159]

[1029.154] Script(S):LOCALS
[@ITERATOR@] 3
[refs] ARRAY
[ammoType2] "sniper"
[@ITERATOR@] 3
[arr] ARRAY
[ammoType] "sniper"
[ammoIndex] 5
[this] TABLE
[movers] ARRAY
[lootbins] ARRAY
[this] TABLE

DIAGPRINTS

**Comment by endergreen12** [comment]
https://github.com/ColombianGuy/r5_flowstate/commit/dfb894399daeb1fd4ca0fa043718608bb5baaf5e
I have identified the problem and fixed it in the above commit
Please update your script and try again
