### ISSUE TITLE
GetOwnerName() may cause server crash

### ISSUE THREAD

**Issue by dxalyjz** [ColombianGuy/r5_aimtrainer#8]
error log:

> [10453.629] Script(S):SCRIPT ERROR: [SERVER] Index "0" is beyond array size of 0
[10453.629] Script(S): -> return file.mAdmins[0]
[10453.630] Script(S):
CALLSTACK
*FUNCTION [GetOwnerName()] gamemodes/custom_tdm/_gamemode_flowstate.nut line [2388]
*FUNCTION [ClientCommand_Scoreboard()] gamemodes/custom_tdm/_gamemode_flowstate.nut line [2837]
[10453.630] Script(S):LOCALS
[this] TABLE
[ping] 242.82678222656
[args] ARRAY
[player] ENTITY (player 8grshjj67543lj [3] (player "8grshjj67543lj" at <11391.1 4475.57 -4303.97>))
[this] TABLE
DIAGPRINTS

if file.mAdmins is null that will cause crash,please fix it

**Comment by CoolSlimbo** [comment]
This looks to be a tdm issue, not an aim trainer issue.

**Comment by dxalyjz** [comment]
> sorry about that , but i can't find the author on github

**Comment by CafeFPS** [comment]
> > sorry about that , but i can't find the author on github
Fix:
Download updated playlist for hosters: https://github.com/ColombianGuy/r5_aimtrainer/releases/tag/Release
Set Admins field correctly in custom_tdm
